config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  # Backoffice
  namespace :backoffice do
    get 'dashboards', to: 'dashboards#index' , as: :root

    # # Personalized routes for Settings
    # resources :settings, only: :index do
    #   collection do
    #     # get 'some', as: 'some'
    #   end
    # end

    # resources :prototypes
    resources :categories
    resources :items
  end

  root to: 'pages#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: { minimum: 6 }
  
  enum role: [:admin, :manager, :operator]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :items

  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :category

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout :layout_by_resource
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    backoffice_root_path
  end
    
  def layout_by_resource
    if devise_controller?
      "sessions"
    else
      "application"
    end
  end
  
  protected

  def configure_permitted_parameters
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end  
end

app/controllers/backoffice/categories_controller.rb
# app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  #include CableReady::Broadcaster
  include ModelName

  def index
    #@resources = Category.includes(:items).all.order(created_at: :desc)
    @resources = Category.all.order(created_at: :desc)
    @resource  = Category.new
  end

  def create
    # category = Category.create(resource_params)
    # cable_ready["stream_categories"].insert_adjacent_html(
    #   selector: "#stream_categories",
    #   position: "afterbegin",
    #   html: render_to_string(
    #     partial: "backoffice/categories/resource",
    #     locals: { resource: category }
    #   )
    # )
    # cable_ready.broadcast
  end

  private

  def resource_params
    accessible = []
    accessible << %i[name slug parent parent_id featured]
    params.require(:category).permit(accessible)
  end
end

app/controllers/backoffice/dashboards_controller.rb
# app/controllers/backoffice/dashboards_controller.rb
class Backoffice::DashboardsController < BackofficeController
  def index
  end
end

app/controllers/backoffice/items_controller.rb
# app/controllers/backoffice/items_controller.rb
class Backoffice::ItemsController < BackofficeController
  include CrudController
  include ModelName

  def index
    @resource ||= Item.new
  end

  def edit
  end  
  
  private

  def resource_params
    accessible = []
    accessible << [:title, :description, :slug, :active, :category, :featured]
    #accessible << [variant_attributes: [:quantity, :wholesale_enabled, :wholesale_quantity]]
    params.require(:item).permit(accessible)
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!

  # layout "backoffice"
  prepend_view_path "app/views/backoffice"
 end

app/controllers/concerns/crud_controller.rb
module CrudController
  extend ActiveSupport::Concern

  included do
    before_action :set_resource_class
    before_action :set_index, only: :index
    before_action :set_show, only: [:show, :edit, :update, :destroy]
  end

  def index
    @resource ||= resource_class.new
  end

  def show; end

  def new
    @resource = resource_class.new
  end

  def edit; end

  def create
    @resource = resource_class.new(resource_params)
    if @resource.save
      flash[:notice] = I18n.t('views.common.created.success', name: resource_class.model_name.human)
      redirect_to "/" + controller_path
    else
      flash[:error] = I18n.t('views.common.created.error', name: resource_class.model_name.human)
      render :new
    end
  end

  def update
    if @resource.update(resource_params)
      flash[:notice] = I18n.t('views.common.updated.success', name: resource_class.model_name.human)
      redirect_to "/" + controller_path
    else
      flash[:error] = I18n.t('views.common.updated.error', name: resource_class.model_name.human)
      render :edit
    end

  end

  def destroy
    if @resource.destroy
      flash[:notice] = I18n.t('views.common.destroyed.success', name: resource_class.model_name.human)
      redirect_to "/" + controller_path
    else
      flash[:error] =  I18n.t('views.common.destroyed.error', name: resource_class.model_name.human)
      render :edit
    end
  end

  private

  def resource_class
    controller_path.classify.delete_prefix("Backoffice::").constantize
  end

  def set_index
    # params[:order] = :created_at, :updated_at
    # params[:sort] = :asc, :desc
    order = params[:order].present? ? params[:order].to_s : "updated_at"
    sort  = params[:sort].present? ? params[:sort].to_s : "desc"

    @resources = @resource_class.all
    #@resources = @resource_class.all.page(params[:page])
    #@resources = @resources.unscope(:order).order("#{order} #{sort}") if params[:order].present?
  end

  def set_show
    @resource = resource_class.find(params[:id])
  end

  def set_resource_class
    @resource_class = resource_class
  end
end

app/controllers/concerns/frontend_controller.rb
module FrontendController
  extend ActiveSupport::Concern

  included do
    before_action :set_resource_class
    before_action :set_index, only: :index
    before_action :set_show, only: [:show, :edit, :update, :destroy]
  end

  def index; end

  def show; end

  private

  def resource_class
    controller_path.classify.constantize
  end

  def set_index
    # params[:order] = :created_at, :updated_at
    # params[:sort] = :asc, :desc
    order = params[:order].present? ? params[:order].to_s : "updated_at"
    sort  = params[:sort].present? ? params[:sort].to_s : "desc"

    @resources = @resource_class.all
    #@resources = @resource_class.all.page(params[:page])
    #@resources = @resources.unscope(:order).order("#{order} #{sort}") if params[:order].present?
  end

  def set_show
    @resource = resource_class.find(params[:id])
  end

  def set_resource_class
    @resource_class = resource_class
  end
end

app/controllers/concerns/model_name.rb
module ModelName
  extend ActiveSupport::Concern

  included do
    before_action :model_class, only: [:index, :show, :new, :edit]
  end

  private
    def model_class
      @model_class = controller_path.classify.delete_prefix("Backoffice::").constantize
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # For customizing title use <% provide(:title, "Page Name") %>
  def seo_title(page_title = '')
    base_title = "Website Title for SEO"
    if page_title.empty? 
      base_title
    else
      [page_title, base_title].join(" | ")
    end
  end
end

app/helpers/backoffice_helper.rb
module BackofficeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/backoffice/dashboards/index.html.erb
<div class="row">
  <div class="col-12">
    <button class='btn btn-light bg-white rounded-pill shadow-sm px-4 mb-4' id='sidebarCollapse' type='button'>
      <i class='fa fa-bars mr-2'></i>
      <small class='text-uppercase font-weight-bold'>Toggle</small>
    </button>

    <p class='mb-5'>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>

    <p class='mb-5'>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>    

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerceOS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="eCommerce OS - Backoffice">

    <title><%= seo_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700;1,800&display=swap" rel="stylesheet">

    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css" integrity="sha384-DhY6onE6f3zzKbjUPRc2hOzGAdEf4/Dz+WJwBvEYL/lkkIsI3ihufq9hk9K4lVoK" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper.js -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/js/bootstrap.bundle.min.js" integrity="sha384-BOsAfwzjNJHrJ8cZidOg56tcQWfp6y72vEJ8xQ9w6Quywb24iOsW913URv1IS4GD" crossorigin="anonymous"></script>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>

    <%= yield :head %>

    <style type="text/css">
      html, body { height: 100%; }

      body {
        display: flex;
        align-items: center;
        padding-top: 40px;
        padding-bottom: 40px;
      }

      .form-signin {
        width: 100%;
        max-width: 830px;
        padding: 15px;
        margin: auto;
      }
      .form-signin .checkbox {
        font-weight: 400;
      }
      .form-signin .form-control {
        position: relative;
        box-sizing: border-box;
        height: auto;
        padding: 8px 15px;
        font-size: 14px;
      }
      .form-signin .form-control:focus {
        z-index: 2;
      }
      .form-signin input[type="email"] {
        margin-bottom: -1px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
      }
      .form-signin input[type="password"] {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
      } 
    </style>
  </head>

  <body>
    <main class="form-signin row">
      <div class="col-6 mx-auto">  
        <%= yield %>
      </div>
    </main>

    <%= javascript_pack_tag 'app' %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="row">
  <div class="col-3 text-center mx-auto mt-5">
    <%= link_to "Log in", new_admin_session_path, class: "btn btn-secondary" %>
  </div>

  <% if admin_signed_in? %>
    <div class="col-3 text-center mx-auto mt-5">
      <%= link_to "Dashboards", backoffice_root_path, class: "btn btn-primary" %>
    </div>

    <div class="col-3 text-center mx-auto mt-5">
      <%= link_to "Logout", destroy_admin_session_path, method: :delete, class: "btn btn-dark" %>
    </div>    
  <% end %>
</div>